export const isDesktop = typeof process !== 'undefined' && 
  (process.env.DESKTOP === '1' || process.env.NWJS === '1');

export type {
  Booking,
  InsertBooking,
  DeviceConfig,
  InsertDeviceConfig,
  PricingConfig,
  InsertPricingConfig,
  HappyHoursConfig,
  InsertHappyHoursConfig,
  HappyHoursPricing,
  InsertHappyHoursPricing,
  FoodItem,
  InsertFoodItem,
  StockBatch,
  InsertStockBatch,
  BookingHistory,
  InsertBookingHistory,
  User,
  InsertUser,
  UpsertUser,
  Expense,
  InsertExpense,
  ActivityLog,
  InsertActivityLog,
  Notification,
  InsertNotification,
  GamingCenterInfo,
  InsertGamingCenterInfo,
  GalleryImage,
  InsertGalleryImage,
  Facility,
  InsertFacility,
  Game,
  InsertGame,
  LoadMetric,
  InsertLoadMetric,
  LoadPrediction,
  InsertLoadPrediction,
  RetentionConfig,
  InsertRetentionConfig,
  DeviceMaintenance,
  InsertDeviceMaintenance,
  PaymentLog,
  InsertPaymentLog,
  SessionGroup,
  InsertSessionGroup
} from "./schema";

export {
  bookings,
  deviceConfigs,
  pricingConfigs,
  happyHoursConfigs,
  happyHoursPricing,
  foodItems,
  stockBatches,
  bookingHistory,
  users,
  expenses,
  activityLogs,
  notifications,
  gamingCenterInfo,
  galleryImages,
  facilities,
  games,
  loadMetrics,
  loadPredictions,
  retentionConfig,
  deviceMaintenance,
  paymentLogs,
  sessionGroups
} from "./schema";
